---
- name: Traefik | Create helm values config
  host: node1
  template:
    src: traefik.yml
    dest: /tmp/traefik.yml

- name: Traefik | Install helm chart
  host: node1
  shell: "helm install -n traefik --namespace kube-system --values /tmp/traefik.yml --set acme.dnsProvider.digitalocean.DO_AUTH_TOKEN={{ digitalocean_api_token }} stable/traefik"

