---
- name: "Digital Ocean Cloud Controller Manager | Config Check | digitalocean_api_token"
  fail:
    msg: "digitalocean_api_token is missing"
  when: (digitalocean_api_token is not defined or digitalocean_api_token == "")
